export default {
  restaurantreview: [
    {
      //id: uuid(),
      //  rid: "CC1049",
      restaurant: "Food Stall",
      food: ["Chicken Rice", "Duck Rice"],
      price: 30.5,
      payment: "Cash",
      rrating: "3/5",
      rreview: "Ok",
      date: "20/3/2020",
    },
    {
      // id: uuid(),
      // rid: "CC1049",
      restaurant: "Food Stall",
      food: ["Chicken Rice", "Duck Rice"],
      price: 30.5,
      payment: "Credit Card",
      rrating: "3.3/5",
      rreview: "Nice",
      date: "20/3/2020",
    },
    {
      //id: uuid(),
      // rid: "CC1049",
      restaurant: "Food Stall",
      food: ["Chicken Rice", "Duck Rice"],
      price: 30.5,
      payment: "Cash",
      rrating: "5/5",
      rreview: "Yummy",
      date: "20/3/2020",
    },
    {
      // id: uuid(),
      // rid: "CC1049",
      restaurant: "Food Stall",
      food: ["Chicken Rice", "Duck Rice"],
      price: 30.5,
      payment: "Cash",
      rrating: "1/5",
      rreview: "Nice",
      date: "20/3/2020",
    },
    {
      // id: uuid(),
      //  rid: "CC1049",
      restaurant: "Food Stall",
      food: ["Chicken Rice", "Duck Rice"],
      price: 30.5,
      payment: "Cash",
      rrating: "4/5",
      rreview: "Nice",
      date: "20/3/2020",
    },
    {
      // id: uuid(),
      //  rid: "CC1049",
      restaurant: "Food Stall",
      food: ["Chicken Rice", "Duck Rice"],
      price: 30.5,
      payment: "Cash",
      rrating: "2/5",
      rreview: "Nice",
      date: "20/3/2020",
    },
  ],
};
