export default {
  restaurantreview: [
    {
      //id: uuid(),
      //  rid: "CC1049",
      restaurant: "Food Stall",
      food: ["Chicken Rice", "Duck Rice"],
      price: 30.5,
      payment: "Cash",
      rrating: "3/5",
      rreview: "Ok",
      date: "20/3/2020",
    },
    {
      // id: uuid(),
      // rid: "CC1049",
      restaurant: "MacDonalds",
      food: ["Happy Meal"],
      price: 4.9,
      payment: "Credit Card",
      rrating: "3.3/5",
      rreview: "Nice",
      date: "2/3/2020",
    },
    {
      //id: uuid(),
      // rid: "CC1049",
      restaurant: "Punggol Nasi Lemak",
      food: ["Nasi Lemak"],
      price: 5.3,
      payment: "Cash",
      rrating: "5/5",
      rreview: "Yummy",
      date: "9/1/2020",
    },
    {
      // id: uuid(),
      // rid: "CC1049",
      restaurant: "FongSeng",
      food: ["Ice Milo, Teriyaki Set"],
      price: 6.8,
      payment: "Cash",
      rrating: "1/5",
      rreview: "Nice",
      date: "20/3/2020",
    },
    {
      // id: uuid(),
      //  rid: "CC1049",
      restaurant: "Al Amaans",
      food: ["Kampong Fried Rice"],
      price: 4.8,
      payment: "Cash",
      rrating: "4/5",
      rreview: "Nice",
      date: "5/3/2020",
    },
    {
      // id: uuid(),
      //  rid: "CC1049",
      restaurant: "Lao Ban Beancurd",
      food: ["Beancurd"],
      price: 1.5,
      payment: "Cash",
      rrating: "2/5",
      rreview: "Nice",
      date: "23/3/2020",
    },
  ],
};
